version: "3.8"

services:
  app:
    build: .
    container_name: iris_api
    ports:
      - "8001:8000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    volumes:
      - .:/app  # hot reload: mount current folder into container

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana3
    ports:
      - "3001:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge